In [2]:
import os
import subprocess
import json
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib import colors as mlp_colors
import random


In [3]:
# same function from HW3 to download files
group_num = 9
def download_files(group_num, folders = None, redownload = False):
    node_names = {}
    root_folder = f"Group{group_num}"
    root_folder_exist = os.path.exists(root_folder)
    if (not root_folder_exist) or redownload:
        os.system(f"rm -rf {root_folder}")
        os.mkdir(root_folder)
        if folders is None:
            folders = ['Facebook-Ego', 'Twitter-Ego']
        for folder in folders:
            os.mkdir(os.path.join(root_folder, folder))
            res = subprocess.run(["curl", "-s", f"https://api.github.com/repos/1250326/exercise_complex_network/contents/Datasets/Group{group_num}/{folder}"], stdout=subprocess.PIPE)
            for file_info in json.loads(res.stdout):
                os.system(f"wget -O {os.path.join(root_folder, folder, (fname:=file_info['name']))} {file_info['download_url']} -q")
                print(f"Downloaded file: {fname}")
                # if '.' in fname:
                    # node_names[folder.split('-')[0]] = fname.split('.')[0]
            print(f"Downloaded folder: {folder}")
    
        
    for folder in os.listdir(root_folder):
        for file in os.listdir(os.path.join(root_folder, folder)):
            if '.' in file:
                node_names[folder.split('-')[0]] = file.split('.')[0]
    return node_names

node_names = download_files(group_num, redownload=False)
node_names

Downloaded file: 3437_2.edges
Downloaded file: 3437_2.egofeat
Downloaded file: 3437_2.feat
Downloaded file: 3437_2.featnames
Downloaded file: Description
Downloaded folder: Facebook-Ego
Downloaded file: 6408382.circles
Downloaded file: 6408382.edges
Downloaded file: 6408382.egofeat
Downloaded file: 6408382.feat
Downloaded file: 6408382.featnames
Downloaded file: Description
Downloaded folder: Twitter-Ego


{'Facebook': '3437_2', 'Twitter': '6408382'}

# Question A

Please randomly choose two sets of nodes in Facebook-Ego dataset (each consists of 50 nodes
without repetition), and calculate the cut size and conductance between the two sets of nodes.
Please also plot the partitioning

In [93]:
n = 50
facebook_net = nx.read_edgelist(f"Group{group_num}/Facebook-Ego/{node_names['Facebook']}.edges")


set1 = random.sample(list(facebook_net.nodes), k=n)
set2 = random.sample(list(facebook_net.nodes), k=n)

assert len(set(set1)) == len(set(set2)) == n, f"{len(set(set1))=} != {len(set(set2))=} != {n=}"

cut_size = nx.cut_size(facebook_net, set1, set2, weight='weight')
print(f"Cut size: {cut_size}")

Cut size: 89


# Question B

Please repeat the process mentioned in (a) again but with different sets of nodes. What differences
have you observed? What cause the differences?

In [95]:
set1 = random.sample(list(facebook_net.nodes), k=n)
set2 = random.sample(list(facebook_net.nodes), k=n)

assert len(set(set1)) == len(set(set2)) == n, f"{len(set(set1))=} != {len(set(set2))=} != {n=}"

cut_size = nx.cut_size(facebook_net, set1, set2, weight='weight')
print(f"Cut size: {cut_size}")

# what caused the cut size to be different?
# the cut size is different because the nodes are randomly selected, so the cut size will be different each time
# the cut size is the number of edges that connect the two sets, so the cut size will be different each time the nodes are randomly

Cut size: 115


# Question C

Please output the Laplacian matrix of Facebook-Ego dataset.

In [100]:
laplacian_matrix = nx.laplacian_matrix(facebook_net)
print(laplacian_matrix.toarray())

[[11 -1  0 ...  0  0  0]
 [-1 11  0 ...  0  0  0]
 [ 0  0 18 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  1]]


# Question D

Please return the list of cliques over the entire Facebook-Ego dataset.

In [103]:
cliques = list(nx.find_cliques(facebook_net))
print(*sorted(cliques, key=len), sep='\n')

['3651', '3683']
['3620', '3714']
['3652', '3614']
['3673', '3612']
['3615', '3664']
['3616', '3699']
['3654', '3697']
['3654', '3703']
['3654', '3633']
['3700', '3669']
['3659', '3642']
['3659', '3637']
['3659', '3610']
['3600', '3612']
['3732', '3610']
['3632', '3720']
['3664', '3696']
['3675', '3708']
['3653', '3720']
['3679', '3585']
['3679', '3624']
['3634', '3593']
['3624', '3662']
['3592', '3626']
['3592', '3589']
['3592', '3677']
['3682', '3662']
['3660', '3610']
['3724', '3617']
['3606', '3727']
['3606', '3662']
['3694', '3608']
['3610', '3674']
['3690', '3617', '3584']
['3690', '3617', '3680']
['3690', '3617', '3622']
['3652', '3665', '3676']
['3706', '3593', '3648']
['3706', '3705', '3714']
['3630', '3602', '3634']
['3629', '3698', '3728']
['3645', '3601', '3604']
['3645', '3601', '3623']
['3645', '3617', '3604']
['3645', '3617', '3680']
['3625', '3672', '3684']
['3685', '3698', '3644']
['3685', '3698', '3598']
['3623', '3593', '3601']
['3689', '3621', '3721']
['3621', '3721